name: Build Pull Request

on: pull_request

jobs:
  test_job:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout@v3
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          # cache: 'gradle'

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Kotlin lint
        run: ./gradlew ktlintCheck --stacktrace
        shell: ${{ inputs.shell }}

      - name: Unit tests
        run: ./gradlew test --stacktrace
        shell: ${{ inputs.shell }}

      - name: Gradle checks
        run: ./gradlew check --stacktrace
        shell: ${{ inputs.shell }}