name: Build Pull Request

on: pull_request

jobs:
  test_job:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout@v3
        uses: actions/checkout@v3

      - name: Init JDK
        uses: ./.github/actions/job/setup-jdk

      - name: Init cache
        uses: ./.github/actions/job/setup-cache

      - name: Kotlin lint
        uses: ./.github/actions/gradle/ktlint
        with:
          shell: ${{ env.shell }}

      - name: Unit tests
        uses: ./.github/actions/gradle/unit-tests
        with:
          shell: ${{ env.shell }}

      - name: All checks
        uses: ./.github/actions/gradle/check
        with:
          shell: ${{ env.shell }}